spring:
  application:
    name:store
stripe:
  apiUrl=https://api.stripe.com
  enabled=true
  timeout=1000
  supported-currencies=USD,JYP
  payment-gateway=stripe
mail:
  host: smtp.gmail.com
  port: 587